### ISSUE TITLE
Conflicts with mod huge structure blocks

### ISSUE THREAD

**Issue by sybsysj** [SGUDestiny/SecretsOfTheVoid#1]
Crashes when play with huge structure blocks mod
https://modrinth.com/mod/huge-structure-blocks

-- huge-structure-blocks-1.0.9-forge
-- citadel-2.6.0-1.20.1
-- geckolib-forge-1.20.1-4.4.7
-- secretsofthevoid-1.20.1-1.3
-- alexscaves-2.0.2

**Comment by SGUDestiny** [comment]
Logs?

**Comment by sybsysj** [comment]
[logs.zip](https://github.com/user-attachments/files/17600499/logs.zip)

**Comment by sybsysj** [comment]
This is my Chinese translation. I only know a little English.There are other translations available before. XD
[zh_cn.json](https://github.com/user-attachments/files/17600821/zh_cn.json)

**Comment by sybsysj** [comment]
This is the Chinese translation. I only know a little English.You can use it before there are other translations available. XD
[zh_cn.json](https://github.com/user-attachments/files/17600909/zh_cn.json)

**Comment by SGUDestiny** [comment]
Try this build and see if the issue persists. I disabled the mixin that causes the crash as it was useless anyway
https://drive.google.com/file/d/14AXl_PgzZpK-1HxL9uZqM6WZbiWPpxLw/view?usp=sharing

**Comment by sybsysj** [comment]
[log.zip](https://github.com/user-attachments/files/17605202/log.zip)

**Comment by SGUDestiny** [comment]
Yeah no... Now it yells at another mixin. I have no idea. I think the structure blocks mod might be just breaking mixins somehow
